coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 3%
    patch:
      default:
        target: auto
        threshold: 3%

comment:
  layout: "reach, diff, flags, files"
  behavior: default

ignore:
  - "**/*_test.go"
  - "examples/**"
  - "benchmarks/**"
